### ISSUE TITLE
Review OLTS mentorship exit survey

### ISSUE THREAD

**Issue by stephwright** [mozillascience/plan#98]
Making exit survey for most recent round of OLTS mentorship : NOT DONE YET STILL LOTS TO CHANGE: https://docs.google.com/form/d/e/1FAIpQLSczY6OtHuKXonq9skP6S36_m8e1S6MffAwi21IfSOZ9NX_cXQ/viewform 
(copied from last round)

    What should I include in the OLTS exit survey?

**Comment by auremoser** [comment]
The link 404s for me @stephwright.
I would say including the following isn't a bad idea, though perhaps you already did, feel free to ignore:
- what did you learn from this experience?
- of what you learned, what would you feel comfortable teaching?
- what did we miss? what opportunities in leadership were not covered?
- how would you like to be involved in the future (checkboxes... guest on community call? mentor for next round? project lead for global sprint? working open workshop session trainer)
- what communities would you like us to collaborate with as we evolve this curriculum? (might be a stretch, but I'd love to see what else they'd recommend, maybe there's a partner we can run a wow with, somewhere in the suggestions)

**Comment by stephwright** [comment]
hrm... it 404s for me now too...

**Comment by abbycabs** [comment]
correct link: https://docs.google.com/forms/d/e/1FAIpQLSczY6OtHuKXonq9skP6S36_m8e1S6MffAwi21IfSOZ9NX_cXQ/viewform

**Comment by auremoser** [comment]
Thanks!
My thoughts (feel free to ignore them, you have more experience with this community than I do):

* If this is what we used before we should totally use it again for consistency... having a bunch of similarly structured data would be great across programs
* Maybe to minimize question count we reduce free text fields asking "how can we improve/what could we do better next time" to one question. They can provide the most salient improvements in the same text field and they'll zip through the survey faster, it will also be easier for us to process that feedback if it's all in the same field.
* Likert Scale questions are always a bit confusing to me because you either are positive, negative, or neutral about most experiences and I'm not sure if we gain anything from having the intermediate 2s and 4s (but again, I might be wrong there, happy to hear a push-back). I just feel like people tend to pick "4" unless they thought things were spectacular, and that decision usually has more to do with their reflex in filling out surveys than their actually opinion of the question.
* I like the NPS question at the end, but could we also ask them to recommend someone specific (with contact info) for a future cohort?

**Comment by stephwright** [comment]
+1 on consistency w/ some changes
also +1 on reduction of duplicative questions and integrating into one ?

Going to recommend keeping 5 pt Likert because research has shown the 5-pt is more likely to be answered... folks want more than just +/-, they also want an in-between, and apparently they also want more than just extremes and a middle.  To compensate, when analyzing a 5-pt Likert, most folks lump 4 & 5 and 1& 2 together for positive/negative average #s.

+1 on asking for recommendations for others to contact for future cohort.

**Comment by abbycabs** [comment]
Thanks all! Very helpful!
